version: '3.8'

services:
    bot:
        build: .
        image: reverse_tg
        restart: always
        env_file:
            - .env
        container_name: reverse_tg
        volumes:
            -  reversed_logs:/logs

volumes:
    reversed_logs:
